import { test, expect } from '@playwright/test';

test('two browser windows share edits, enforce roles, refresh, and reconnect', async ({ browser, page: owner }, testInfo) => {
  const candidateContext = await browser.newContext();
  const candidate = await candidateContext.newPage();
  const errors = [];
  owner.on('pageerror', error => errors.push(error.message));
  candidate.on('pageerror', error => errors.push(error.message));
  try {
    await owner.goto('/');
    await owner.getByRole('button', { name: /Create session/ }).click();
    await expect(owner.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'false');
    const invitation = await owner.getByLabel('Candidate invitation', { exact: true }).inputValue();
    await candidate.goto(invitation);
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'false');
    await expect(owner.getByText('Candidate connected', { exact: true })).toBeVisible();
    await expect(candidate.getByText('Interviewer connected', { exact: true })).toBeVisible();
    await expect(candidate.getByLabel('Problem statement', { exact: true })).toHaveAttribute('readonly', '');
    await expect(candidate.getByRole('button', { name: /Copy candidate/ })).toHaveCount(0);
    const timings = [];
    let start = Date.now();
    await owner.getByLabel('Problem statement', { exact: true }).fill('Return the sum of two numbers.');
    await expect(candidate.getByLabel('Problem statement', { exact: true })).toHaveValue('Return the sum of two numbers.', { timeout: 1000 });
    timings.push(Date.now() - start);
    start = Date.now();
    await candidate.getByRole('textbox', { name: 'Shared code' }).fill('function sum(a, b) { return a + b; }');
    await expect(owner.getByRole('textbox', { name: 'Shared code' })).toHaveText('function sum(a, b) { return a + b; }', { timeout: 1000 });
    timings.push(Date.now() - start);
    start = Date.now();
    await owner.getByRole('textbox', { name: 'Shared code' }).fill('const sum = (a, b) => a + b;');
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveText('const sum = (a, b) => a + b;', { timeout: 1000 });
    timings.push(Date.now() - start);
    expect(timings.every(ms => ms < 1000)).toBe(true);
    await candidate.getByRole('combobox', { name: 'Language' }).selectOption('python');
    await expect(owner.getByRole('combobox', { name: 'Language' })).toHaveValue('javascript');
    await expect(owner.getByText('Saved on server', { exact: true })).toBeVisible();
    await candidate.reload();
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'false');
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveText('const sum = (a, b) => a + b;');
    await expect(candidate.getByRole('combobox', { name: 'Language' })).toHaveValue('javascript');
    await candidateContext.setOffline(true);
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'true');
    await expect(owner.getByText('Candidate not connected', { exact: true })).toBeVisible();
    await owner.getByLabel('Problem statement', { exact: true }).fill('Updated while candidate was offline.');
    await expect(owner.getByText('Saved on server', { exact: true })).toBeVisible();
    await candidateContext.setOffline(false);
    await expect(candidate.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'false');
    await expect(candidate.getByLabel('Problem statement', { exact: true })).toHaveValue('Updated while candidate was offline.');
    await expect(owner.getByText('Candidate connected', { exact: true })).toBeVisible();
    await owner.reload();
    await expect(owner.getByRole('textbox', { name: 'Shared code' })).toHaveAttribute('aria-readonly', 'false');
    await expect(owner.getByLabel('Problem statement', { exact: true })).toHaveValue('Updated while candidate was offline.');
    await candidate.screenshot({ path: testInfo.outputPath('candidate.png'), fullPage: true });
    console.log(`Live edit propagation (problem, candidate code, interviewer code): ${timings.join(', ')} ms`);
    await candidate.goto(invitation + 'invalid');
    await expect(candidate.getByRole('heading', { name: 'Session not found or link invalid' })).toBeVisible();
    expect(errors).toEqual([]);
  } finally { await candidateContext.close(); }
});
